spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:dinnervery;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# 비즈니스 설정
business:
  hours:
    open-time: "15:30"
    close-time: "22:00"
    last-order-time: "21:30"
    delivery-start-time: "16:00"
    delivery-end-time: "22:00"
    min-delivery-minutes: 30
    delivery-time-unit: 10
  menu:
    special-dishes:
      champagne-festival-dinner:
        name: "샴페인 축제 디너"
        price: 90000
  customer:
    vip-discount-rate: 10
