spring:
  datasource:
    url: jdbc:mysql://<HOST>:3306/dinnervery?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: <USER>
    password: <PASS>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging.level.org.hibernate.SQL: info


